Update sync.private.js
twilio-professional-services/flex-project-template pull request #118
Opened 2022-12-09 15:53 UTC by mirobotur

Sync MapItem handlers

### Summary

_Provide a summary of the change..._

### Checklist
- [x ] Tested changes end to end
- [ x] Added PR Label "ready-for-review"
- [ x] Requested one or more reviewers for the PR

2022-12-09 20:51 UTC, dremin requested changes
LGTM functionality-wise, just a few comments/strings to clean up!

2022-12-09 20:51 UTC, dremin commented on serverless-functions/src/functions/common/twilio-wrappers/sync.private.js
> + * @returns {object} A new Sync Map Item
Does this actually return a map item? I'd generally expect a delete to just return success/status, but the documentation doesn't indicate anything is returned.

2022-12-09 20:51 UTC, dremin commented on serverless-functions/src/functions/common/twilio-wrappers/sync.private.js
> +    throw "Invalid parameters object passed. Parameters must contain context object";
This should say 'mapSid' rather than 'context'. Same goes for this line in the other functions below.

2022-12-09 20:51 UTC, dremin commented on serverless-functions/src/functions/common/twilio-wrappers/sync.private.js
> +    throw "Invalid parameters object passed. Parameters must contain uniqueName string value";
This should say 'key' rather than 'uniqueName'. Same goes for this line in the other functions below.

2022-12-09 20:51 UTC, dremin commented on serverless-functions/src/functions/common/twilio-wrappers/sync.private.js
> + * @returns {object} A new Sync Map Item
Returns existing sync map item?

2022-12-09 20:51 UTC, dremin commented on serverless-functions/src/functions/common/twilio-wrappers/sync.private.js
> +    return { success: true, status: 200, mapItem: mapItem };
I don't think a map item is returned by the API so you might not need to return anything other than success/status.

2022-12-13 08:53 UTC, mirobotur commented
@dremin Yeah, sorry. I did copy/paste... Not sure if I fixed it properly here.

2022-12-13 14:47 UTC, dremin approved these changes
Looks good!

2022-12-13 14:48 UTC, merged