Agent Assistance feature added to Supervisor Plugin Suite
twilio-professional-services/flex-project-template pull request #162
Opened 2023-03-15 14:26 UTC by aestellwag

### Summary

_Provide a summary of the change..._

### Checklist
- [ x ] Tested changes end to end
- [ x ] Any config changes added to all environment files
- [ x ] For Flex features added, ensure the feature list on the README on the project root folder is updated
- [ x ] Completed README template for new features
  - [ x ] Feature summary - _high level summary of what the feature does_
  - [ x ] Flex User Experience with animations - _animations with descriptions if necessary of the user experience in Flex_
  - [ x ] Setup and dependencies - _description of any setup steps required for this feature_
  - [ x ] How does it work? - _description of plumbing supporting feature_
- [ x ] Added PR Label "ready-for-review"
- [ x ] Requested one or more reviewers for the PR

2023-03-15 20:05 UTC, mschmitt19 requested changes
Great addition overall -- minor tweaks and comments, but great work! 💪

2023-03-15 20:42 UTC, aestellwag commented on plugin-flex-ts-template-v2/src/feature-library/supervisor-barge-coach/screenshots/Supervisor-Barge-Coach-Plugin-9.gif
I'm not in love with where this toggle is, I looked to add it within the teams view, but couldn't find a good spot to attach it to.  Open to suggestion.  Reason I made it a hover vs persistent was having that text in the MainHeader seemed like a bad use of that space.  I'm open to suggestions on a better placement!

2023-03-16 16:17 UTC, jhunter-twilio approved these changes
lgtm

2023-03-16 16:57 UTC, dremin commented
A couple thoughts on the new UI elements:

- I think the nav bar alert toggle should be off to the right side with all of the other nav bar accessories. Rather than being a switch, maybe it should be a 'bell' icon in the same style as the device manager feature. Clicking the icon could toggle, or it could open a menu with the toggle switch and a description. This would make it immediately clear the purpose of the toggle, and not look out of place.
- What is the reasoning behind making the request assistance button so large? Why does it deserve to be larger than the other buttons? I don't have a problem with it per se, but we should be deliberate when taking up that much space. I could also see the button fitting in well next to the 'end call' button in the task header.

2023-03-16 17:28 UTC, aestellwag commented
> 

The icon originally was a bell, so I'd be happy to tweak that and shift it to the right.

As for the Agent assistance button in the CallCanvas, I felt having it near the other buttons could cause more mis-clicks.  The sizing difference is unintended, I'll correct that bit.  Happy to shift the button where we felt it would be better suited, I'm not in love with any of the UI I have in place :)

2023-03-17 15:22 UTC, aestellwag commented
New commit that incorporates the recent merge from @dremin to the main branch.

2023-03-17 17:29 UTC, dremin requested changes
I would take another look at the flex-hooks merge, something happened and they got pretty messed up somehow.

2023-03-17 17:29 UTC, dremin commented on plugin-flex-ts-template-v2/src/feature-library/supervisor-barge-coach/custom-components/SupervisorAlertButton/SupervisorAlertButtonComponent.tsx
> +            style={{width:'20px',height:'20px'}}
You can replace the sizings here with `size="small"`. However, the colors are incorrect when compared to the other IconButtons in the MainHeader. It looks like you will want to apply this style: https://code.hq.twilio.com/flex/flex-monorepo/blob/99f28dff50df44f3d33a5d4195a548ab6f674fa1/packages/flex-ui/src/components/MainHeader/MainHeader.Components.ts#L47-L56

2023-03-17 17:29 UTC, dremin commented on plugin-flex-ts-template-v2/src/feature-library/supervisor-barge-coach/flex-hooks/actions/MonitorCall.ts
> +  flex.Actions.addListener("afterMonitorCall", (payload) => {
This should use the interpolated name `${actionEvent}${actionName}`

2023-03-17 17:29 UTC, dremin commented on plugin-flex-ts-template-v2/src/feature-library/supervisor-barge-coach/flex-hooks/actions/MonitorCall.ts
> +export const disableBargeCoachButtonsUponMonitor = async (
This whole export should be deleted.

2023-03-17 17:29 UTC, dremin commented on plugin-flex-ts-template-v2/src/feature-library/supervisor-barge-coach/flex-hooks/actions/StopMonitoringCall.ts
> +export const actionName = FlexAction.MonitorCall;
Somehow this got overwritten with MonitorCall instead of all of the StopMonitorCall logic.

2023-03-17 17:29 UTC, dremin commented on plugin-flex-ts-template-v2/src/feature-library/supervisor-barge-coach/flex-hooks/actions/reservation.ts
It looks like this is a copy of the reservationCreated.ts file in jsclient-event-listeners. This entire file can be deleted--it's in the wrong place, and is not being used because its not defining the necessary exports.

2023-03-17 17:29 UTC, dremin commented on plugin-flex-ts-template-v2/src/feature-library/supervisor-barge-coach/flex-hooks/components/MainHeader.tsx
> +export const componentName = FlexComponent.TaskCanvasTabs;
This is modifying MainHeader, not TaskCanvasTabs

2023-03-17 17:29 UTC, dremin commented on plugin-flex-ts-template-v2/src/feature-library/supervisor-barge-coach/flex-hooks/components/TaskOverviewCanvas.tsx
> +export const componentName = FlexComponent.TaskCanvasTabs;
Somehow this got changed to TaskCanvasTabs instead of TaskOverviewCanvas.

2023-03-17 17:29 UTC, dremin commented on plugin-flex-ts-template-v2/src/feature-library/supervisor-barge-coach/flex-hooks/components/TaskOverviewCanvas.tsx
> +  if(!isFeatureEnabled()) return;
Feature enabled checks are no longer needed.

2023-03-17 17:29 UTC, dremin commented on plugin-flex-ts-template-v2/src/feature-library/supervisor-barge-coach/flex-hooks/components/TeamsView.tsx
This file is named TeamsView, but the export says it modifies CallCanvas, and the code actually modifies WorkersDataTable. These all need to be consistent.

2023-03-17 17:29 UTC, dremin commented on plugin-flex-ts-template-v2/src/feature-library/supervisor-barge-coach/flex-hooks/components/TeamsView.tsx
> +      header={""}
This is where you can fix the Teams view columns getting pushed over. Try adding `style={{width:'22px'}}` (you might want to experiment with different sizes, but that one does seem to look reasonable)

2023-03-17 17:29 UTC, dremin commented on plugin-flex-ts-template-v2/src/feature-library/supervisor-barge-coach/flex-hooks/jsclient-event-listeners/worker-client/reservationCreated.ts
You may want to just revert this whole file and re-add the necessary changes--the necessary exports for feature-loader to find it were removed, and manually adding the reservationCreated listener is no longer needed. See the readme example: https://github.com/twilio-professional-services/flex-project-template/tree/main/plugin-flex-ts-template-v2#jsclient-event-listeners

You may want to even re-write this to use the new Flex event for taskWrapup instead: https://github.com/twilio-professional-services/flex-project-template/tree/main/plugin-flex-ts-template-v2#events

2023-03-17 17:29 UTC, dremin commented on plugin-flex-ts-template-v2/src/feature-library/supervisor-barge-coach/flex-hooks/notifications/BargeCoachAssist.ts
This won't work, please see the readme example for notifications: https://github.com/twilio-professional-services/flex-project-template/tree/main/plugin-flex-ts-template-v2#notifications

2023-03-20 15:53 UTC, aestellwag commented on plugin-flex-ts-template-v2/src/feature-library/supervisor-barge-coach/custom-components/AgentAssistanceButton/AgentAssistanceButtonComponent.tsx
> +      <Tooltip text={ agentAssistanceButton ? 'Turn off Assistance' : 'Ask for Assistance'} placement="right">
Original thought was if the agent no longer needed assistance, they have the ability to turn this off.  I do like the idea of having the supervisor resolve the alert.  I can look to add that in the future.

2023-03-21 20:50 UTC, dremin approved these changes
lgtm!

2023-03-23 16:01 UTC, merged