Add external directory
twilio-professional-services/flex-project-template pull request #220
Opened 2023-05-09 20:06 UTC by jared-hunter

### Summary

This adds a configurable external directory option to the worker directory view.  When enabled, it will render for call tasks only.  Cold transfers are handled directly by this feature and warm transfers have a dependency on either the conference feature being enabled or the native external warm transfer feature being enabled.

Due to the dependency on conference, it now provides an action that mirrors the interface for the new StartExterrnalWarmTransfer action and only registers it when the native StartExternalWarrmTransfer is not available.

this feature addresses item raised in #137 

### Checklist
- [x] Tested changes end to end
- [x] Any config changes added to all environment files
- [x] For Flex features added, ensure the feature list on the README on the project root folder is updated
- [x] Completed README template for new features
  - [x] Feature summary - _high level summary of what the feature does_
  - [x] Flex User Experience with animations - _animations with descriptions if necessary of the user experience in Flex_
  - [x] Setup and dependencies - _description of any setup steps required for this feature_
  - [x] How does it work? - _description of plumbing supporting feature_
- [x] Added PR Label "ready-for-review"
- [x] Requested one or more reviewers for the PR

2023-05-09 23:24 UTC, dremin requested changes

2023-05-10 01:24 UTC, jhunter-twilio commented on plugin-flex-ts-template-v2/src/feature-library/custom-transfer-directory/utils/CustomTransferDirectoryService.ts
i thought about this but it was too much for the moment, i just followed the pattern laid out in the ConferenceService.  Might need to chat about what to do here as a guiding principle.

2023-05-10 01:25 UTC, jhunter-twilio commented on plugin-flex-ts-template-v2/src/utils/serverless/PhoneNumbers/PhoneNumberService.ts
> +  };
i think this is valid given a common service state or not

2023-05-10 01:44 UTC, jhunter-twilio commented on plugin-flex-ts-template-v2/src/feature-library/custom-transfer-directory/flex-hooks/custom-actions/startExternalColdTransfer.ts
> +      CustomTransferDirectoryService.startColdTransfer(task.attributes.call_sid, phoneNumber);
agree on error handling piece but sip handling i think we can call as out of scope for just now to get this wrapped up and we can extend support for it later

2023-05-10 01:56 UTC, jhunter-twilio commented on flex-config/ui_attributes.common.json
> +          }]
agreed but like the sip support i want to make this out of scope for now since it is functional enough to use and build on and im running out of time

2023-05-10 16:16 UTC, dremin approved these changes
Looks good! Before merging I'd like to see the external directory disabled by default because it requires config to be useful.

As mentioned in the review comments here are some items that can be followups later:
- Full SIP support
- Component reuse within the feature
- More scalable storage for the directory

2023-05-10 16:34 UTC, merged