Updated Callback to make request for other number
twilio-professional-services/flex-project-template pull request #321
Opened 2023-08-18 14:59 UTC by viralgandhi

### Summary

_Provide a summary of the change..._

### Checklist

- [ ] Tested changes end to end
- [ ] Any config changes added to all environment files
- [ ] Completed README template for new features in `/docs/docs/feature-library/` and added feature row entry into the `/docs/docs/feature-library/00_overview.md` file
  - [ ] Feature summary - _high level summary of what the feature does_
  - [ ] Flex User Experience with animations - _animations with descriptions if necessary of the user experience in Flex_
  - [ ] Setup and dependencies - _description of any setup steps required for this feature_
  - [ ] How does it work? - _description of plumbing supporting feature_
- [ ] Added PR Label "ready-for-review"
- [ ] Requested one or more reviewers for the PR

2023-08-18 16:04 UTC, dremin requested changes
Thanks for working on this @viralgandhi! A couple things to look at:
1. Could you please address the eslint/prettier issues? An easy way to see this locally is to run `npm run lint:fix` (which will auto fix most issues) then run `npm run lint` to see any remaining issues.
2. It looks like the option to choose your number only applies to callbacks and not voicemails. However, voicemails are also a form of callback, so they should also have the option.

2023-08-19 04:25 UTC, viralgandhi commented
@dremin , I've fixed issues related to eslint. can you please explain #2? There will not be able changes to voicemail in my view. Thats why we are checking if `_isVoicemail_` request in `handleCallbackOrVoicemailSelected()`

2023-08-19 06:13 UTC, jhunter-twilio commented
Hi @viralgandhi 

A voicemail is a type of callback. The agent receives the voicemail and calls the customer back. 

I think @dremin was saying that the customer journey for leaving the voicemail should also include an option to set your callback number.

2023-08-21 06:18 UTC, viralgandhi commented
Hi @jhunter-twilio @dremin , Not sure if I understand the usecase here. When end user chooses voicemail option and one is leaving a voicemail saying that 'please call me back on +1xxxxx number' then will it not be duplicate information where you have high chance of getting different number in voicemail vs `numberToCall` field?
We can connect on this to discuss more if needed.

2023-09-12 15:07 UTC, dremin commented
> Hi @jhunter-twilio @dremin , Not sure if I understand the usecase here. When end user chooses voicemail option and one is leaving a voicemail saying that 'please call me back on +1xxxxx number' then will it not be duplicate information where you have high chance of getting different number in voicemail vs `numberToCall` field? We can connect on this to discuss more if needed.

I see what you mean--typically a voicemail includes the number to call in the audio portion. However, if the number to dial is not correct in the task attributes, then the agent would need to manually dial the call back to the original caller, which would cause incorrect reporting. However, that is no worse than the current state of things today, so we can look further into what to do later.

2023-09-12 15:12 UTC, dremin requested changes

2023-09-12 15:12 UTC, dremin commented on serverless-functions/src/functions/features/callback-and-voicemail/studio/wait-experience.protected.js
>    // though technically these could be handled entirely in the waitUrl TwiML
In my opinion, now that the voicemail and callback logic are separate, this function doesn't make sense to handle both any more. Maybe it makes sense to split this function up?

2023-09-12 15:12 UTC, dremin commented on serverless-functions/src/functions/features/callback-and-voicemail/studio/wait-experience.protected.js
> +        gather.say(` press 1 to confirm and 2 to re-enter`);
Can the message string be extracted into the `options.messages` object to allow easier customizing/localizing?

2023-09-12 15:59 UTC, viralgandhi commented
Hi Sam, the scenario you explained that agent may have to manually dial a
call will occur in any case. And we may not cover all cases for reporting.
May be disposition is one of the way. I would more worry about customer
experience that we are asking customer to punch in their phone number AND
record a voicemail. As a customer I would rather goto callback option then.

Regards,
Viral Gandhi

On Tue, 12 Sept, 2023, 8:37 pm Sam Johnson, ***@***.***>
wrote:

> Hi @jhunter-twilio <https://github.com/jhunter-twilio> @dremin
> <https://github.com/dremin> , Not sure if I understand the usecase here.
> When end user chooses voicemail option and one is leaving a voicemail
> saying that 'please call me back on +1xxxxx number' then will it not be
> duplicate information where you have high chance of getting different
> number in voicemail vs numberToCall field? We can connect on this to
> discuss more if needed.
>
> I see what you mean--typically a voicemail includes the number to call in
> the audio portion. However, if the number to dial is not correct in the
> task attributes, then the agent would need to manually dial the call back
> to the original caller, which would cause incorrect reporting. However,
> that is no worse than the current state of things today, so we can look
> further into what to do later.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/twilio-professional-services/flex-project-template/pull/321#issuecomment-1715909176>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAPVD4SOECQPNKOQGQ4VO33X2B3EZANCNFSM6AAAAAA3VUWM5Q>
> .
> You are receiving this because you were mentioned.Message ID:
> <twilio-professional-services/flex-project-template/pull/321/c1715909176@
> github.com>
>

2023-09-12 16:14 UTC, dremin commented
> Hi Sam, the scenario you explained that agent may have to manually dial a call will occur in any case. And we may not cover all cases for reporting. May be disposition is one of the way. I would more worry about customer experience that we are asking customer to punch in their phone number AND record a voicemail. As a customer I would rather goto callback option then. Regards, Viral Gandhi

I agree, for now lets not ask voicemail for the number.

2024-02-02 20:08 UTC, dremin approved these changes
🎉

2024-02-02 20:23 UTC, merged