Ring notification for incoming voice and chat
twilio-professional-services/flex-project-template pull request #330
Opened 2023-08-23 12:25 UTC by viralgandhi

### Summary

_Provide a summary of the change_

### Checklist

- [ ] Tested changes end to end
- [ ] Updated documentation
- [ ] Requested one or more reviewers

2023-08-25 19:05 UTC, jhunter-twilio requested changes
some documentation updates but otherwise its looking good

2023-08-25 19:05 UTC, jhunter-twilio commented on plugin-flex-ts-template-v2/src/feature-library/ring-notification/flex-hooks/jsclinet-event-listeners/worker-client/reservationCreated.ts
Logically this all looks good but the jsclient-event-listeners is really the legacy approach - we should be using the events hooks.  You can see an example [here](https://github.com/twilio-professional-services/flex-project-template/tree/main/plugin-flex-ts-template-v2/src/feature-library/activity-reservation-handler/flex-hooks/events) 

Given the nature of the code, i can see that breaking things out could be significant and unnecessary complexity.

Could you add a comment in the code just acknowledging that using the manager events is the typically preferred approach but this method makes the code much simpler?

2023-08-25 19:05 UTC, jhunter-twilio commented on docs/docs/feature-library/ring-notification.md
Could you enhance the documentation to follow the standard set [here](https://twilio-professional-services.github.io/flex-project-template/feature-library/activity-reservation-handler) and [here](https://twilio-professional-services.github.io/flex-project-template/feature-library/activity-skill-filter)

2023-08-28 05:21 UTC, viralgandhi commented on docs/docs/feature-library/ring-notification.md
Thanks for the feedback @jhunter-twilio , I've updated the comment and document. Let me know if anything else is needed.

2023-09-12 15:25 UTC, dremin requested changes
This looks mostly good to go, just a couple small fixes!

2023-09-12 15:25 UTC, dremin commented on plugin-flex-ts-template-v2/src/feature-library/ring-notification/flex-hooks/jsclinet-event-listeners/worker-client/reservationCreated.ts
@viralgandhi There is a typo in the folder name `jsclinet-event-listeners`, could you please fix it to `jsclient-event-listeners`?

2023-09-12 15:25 UTC, dremin commented on plugin-flex-ts-template-v2/src/feature-library/ring-notification/helpers/audioPlayerManagerHelper.ts
> +      url: `https://${custom_data.serverless_functions_domain}/features/ring-notification/phone_ringing.mp3`,
The URL doesn't work when running `localhost`. If you look at the `chat-to-video` feature's `SwitchToVideo` component you can see an example that works in all scenarios. Could you please adjust the logic here to be the same?

2024-02-01 23:33 UTC, dremin approved these changes
:tada:

2024-02-01 23:38 UTC, merged