DEMOENG-1270 - Restructure template documentation
twilio-professional-services/flex-project-template pull request #358
Opened 2023-09-25 23:47 UTC by dremin

### Summary

Complete overhaul of the documentation structure. Much of the existing content has been retained within the new structure, and there is a fair amount of new content as well.

You can view the updates locally by running `npm run start:docs`.

### Checklist

- [ ] Tested changes end to end
- [ ] Updated documentation
- [x] Requested one or more reviewers

2023-09-30 13:35 UTC, jhunter-twilio requested changes
A huge step in the right direction - a couple minor additions and i think we can fold in these updates and iterate further - its a huge amount to bite off at once as it is, well done!

2023-09-30 13:35 UTC, jhunter-twilio commented on docs/docs/building/template-utilities/shared-sync-client.md
do you think we could add a reference as an example to somewhere leveraging the the shared sync client?

2023-09-30 13:35 UTC, jhunter-twilio commented on docs/docs/04_package-overview.md
is this doc becoming redundant as we have similar information under "Building with the template > Getting Started"?

2023-09-30 13:35 UTC, jhunter-twilio commented on docs/docs/05_changelog.md
should the change log have some updates in here about the TF adjustments for using serverless 😨

2023-10-02 15:38 UTC, dremin commented on docs/docs/building/template-utilities/shared-sync-client.md
Done!

2023-10-02 15:39 UTC, dremin commented on docs/docs/04_package-overview.md
Yes, this doc is largely redundant, but I didn't have a good place to put the information that currently only exists on that page. Open to thoughts on where this info should go!

2023-10-02 15:41 UTC, dremin commented on docs/docs/05_changelog.md
Merged PRs are our changelog, maybe we should get rid of the page?

2023-10-02 18:37 UTC, jhunter-twilio commented on docs/docs/04_package-overview.md
none at the moment, we can defer this decision to later

2023-10-02 18:37 UTC, jhunter-twilio commented on docs/docs/05_changelog.md
that works for me!

2023-10-02 18:40 UTC, dremin commented on docs/docs/05_changelog.md
Done!

2023-10-02 20:19 UTC, jhunter-twilio approved these changes

2023-10-02 21:01 UTC, merged