Worker Canvas Tabs for Skills, Channel Capacity & Worker Attributes
twilio-professional-services/flex-project-template pull request #381
Opened 2023-10-10 13:42 UTC by ldvlgr

### Summary

This enhancement adds Tabs to the Worker Canvas for Skills, Channel Capacity & Worker Attributes.
The existing native WorkerSkills component is removed from the Worker Canvas and added as the first tab.
Supervisor Channel Capacity is moved to the 2nd tab and Worker Attributes viewer to the 3rd tab.
Having tabs here makes the Worker Canvas side panel easier to navigate and opens it up to add the Update Team Name capability!

### Checklist

- [ ] Tested changes end to end
- [ ] Updated documentation
- [ ] Requested one or more reviewers

2023-10-25 18:40 UTC, jhunter-twilio requested changes
this is a great looking feature - some things we need to tidy up to keep it inline with the conventions in the template.

Main issue:
- As it stands attribute-viewer and supervisor-capacity dont work unless you also enable worker-canvas

Reason:
this is because there are no hooks for those features on the worker canvas anymore

Solution:
To fit with the pattern of cross-feature dependencies we have 

if feature B depends on feature A performing operational logic.  Feature A should expose an action that can be invoked by feature B (example of [conversations](https://github.com/twilio-professional-services/flex-project-template/blob/d19828791cade37714d8c8aa249e7ce45fb64184/plugin-flex-ts-template-v2/src/feature-library/conference/flex-hooks/custom-actions/startExternalWarmTransfer.ts#L8) exposing an action for invoking an external warm transfer and [custom-transfer-directory](https://github.com/twilio-professional-services/flex-project-template/blob/d19828791cade37714d8c8aa249e7ce45fb64184/plugin-flex-ts-template-v2/src/feature-library/custom-transfer-directory/custom-components/ExternalDirectoryTab.tsx#L62) using it)

if feature B depends on feature A for rendering location.  Feature B should check if Feature A is enabled, and render appropriately ([example](https://github.com/twilio-professional-services/flex-project-template/blob/d19828791cade37714d8c8aa249e7ce45fb64184/plugin-flex-ts-template-v2/src/feature-library/canned-responses/flex-hooks/components/CRMContainer.tsx#L25) in canned-responses rendering differently depending on presence of enhancedCRMContainer)

In this case its a bit of both....

worker-canvas-tabs should expose an action to register the tab (you can see an example in enhanced crm container, registering the action [here](https://github.com/twilio-professional-services/flex-project-template/blob/d19828791cade37714d8c8aa249e7ce45fb64184/plugin-flex-ts-template-v2/src/feature-library/enhanced-crm-container/flex-hooks/custom-action/loadCRMContainerTabs.ts#L4) and how it is used to hook in components for rendering [here](https://github.com/twilio-professional-services/flex-project-template/blob/d19828791cade37714d8c8aa249e7ce45fb64184/plugin-flex-ts-template-v2/src/feature-library/enhanced-crm-container/flex-hooks/actions/CRMContainerLoaded.tsx#L9)

Then the attribute-viewer and supervisor-capacity features can run independently or with worker-canvas

The alternative solution (and actually my preference) is to combine these features together so that the worker-canvas-tabs piece is always enforced by the feature (why would you not want that?)

so maybe something like a supervisor-worker-canvas-enhancements that brings these al together under one umbrella 

let me know your thoughts

2023-12-15 18:20 UTC, dremin requested changes

2023-12-15 18:20 UTC, dremin commented on plugin-flex-ts-template-v2/package.json
Revert changes to this file

2023-12-15 18:20 UTC, dremin commented on serverless-functions/src/functions/common/twilio-wrappers/taskrouter.private.js
> + */
Add workerSid and attributesUpdate to the comment

2023-12-15 18:20 UTC, dremin commented on plugin-flex-ts-template-v2/src/feature-library/worker-details/custom-components/WorkerDetailsContainer/WorkerDetailsContainer.tsx
> +    <Stack orientation="vertical" spacing="space0">
This could use some spacing on the sides.

2023-12-15 18:20 UTC, dremin commented on plugin-flex-ts-template-v2/src/feature-library/worker-canvas-tabs/flex-hooks/paste-elements/index.ts
I wonder if we can reduce the spacing around tabs some more.

2023-12-15 18:20 UTC, dremin commented on plugin-flex-ts-template-v2/src/feature-library/supervisor-capacity/flex-hooks/components/WorkerCanvas.tsx
> +    tabTitle: StringTemplates.ChannelCapacity,
Maybe we should have a shorter title for the tabs, such as `Capacity`.

2023-12-15 18:20 UTC, dremin commented on plugin-flex-ts-template-v2/src/feature-library/worker-details/custom-components/WorkerDetailsContainer/WorkerDetailsContainer.tsx
> +          </Tr>
This name row seems redundant given the name is already at the top of the profile section.

2024-01-23 23:30 UTC, dremin approved these changes

2024-01-23 23:34 UTC, merged