Add keyboard shortcuts for call recording pause/resume/toggle
twilio-professional-services/flex-project-template pull request #564
Opened 2024-06-04 13:54 UTC by chaosloth

### Summary

Modification to the pause-recording feature to add keyboard shortcuts (and Flex Actions) for:
- Pause call recording on focused task
- Resume call recording on focused task
- Toggle state between pause and resume

### Checklist

- [X] Tested changes end to end
- [X] Updated documentation
- [X] Requested one or more reviewers

2024-06-04 22:13 UTC, dremin requested changes
Thanks so much for adding this functionality! I was actually considering adding these actions myself, so double thanks 😄

All of the comments below should be pretty minor and straightforward, let me know if you have any questions!

2024-06-04 22:13 UTC, dremin commented on plugin-flex-ts-template-v2/src/feature-library/pause-recording/flex-hooks/events/pluginsInitialized.ts
> +  registerResumeCallRecordingAction();
I think the PauseRecordingButton component should be refactored to use these new actions so that everything is using the same code path.

2024-06-05 00:33 UTC, chaosloth commented on plugin-flex-ts-template-v2/src/feature-library/pause-recording/flex-hooks/custom-action/toggleRecording.ts
> +      pausedRecordings.find((pausedRecording) => payload.task && pausedRecording.reservationSid === payload.task.sid)
When I remove this from the condition I'm getting a `ts(18048)` for the clause

2024-06-05 12:14 UTC, chaosloth commented
@dremin Thanks for the review, the above items are now addressed

2024-06-05 15:08 UTC, dremin requested changes
Looks good! Just some missing awaits to fix and it will be done.

2024-06-05 23:21 UTC, chaosloth commented on plugin-flex-ts-template-v2/src/feature-library/pause-recording/custom-components/PauseRecordingButton/PauseRecordingButton.tsx
> +      Actions.invokeAction('PauseCallRecording', { task: props.task });
Take 2 with awaited actions

2024-06-05 23:21 UTC, chaosloth commented on plugin-flex-ts-template-v2/src/feature-library/pause-recording/flex-hooks/custom-action/toggleRecording.ts
> +      Actions.invokeAction('PauseCallRecording', payload);
Take 2 with awaited actions

2024-06-05 23:22 UTC, chaosloth commented
@dremin Sorry about that - now with awaited actions

2024-06-06 16:24 UTC, dremin approved these changes
LGTM! 🎉

2024-06-06 16:25 UTC, merged